export const cards = [
  {
    alt: "a dog",
    src: "https://i.imgflip.com/5s7g8s.png",
    keyword: "Nature",
    title: "Everyone Needs a Special 'Sit Spot' in Nature",
    text: `Ever since I read Richard Louv's influential book, "Last Child in the Woods," the idea of having a special "sit spot" has stuck with me. This advice, which Louv attributes to nature educator Jon Young, is for both adults and children to find...`,
    date: "November 4, 2020",
    source: "treehugger",
    link: "#",
  },
  {
    alt: "a dog",
    src: "https://i.imgflip.com/5s7g8s.png",
    keyword: "Nature",
    title: "Nature makes you better",
    text: `We all know how good nature can make us feel. We have known it for millennia: the sound of the ocean, the scents of a forest, the way dappled sunlight dances through leaves.`,
    date: "November 4, 2020",
    source: "national geographic",
    link: "#",
  },
  {
    alt: "a dog",
    src: "https://i.imgflip.com/5s7g8s.png",
    keyword: "Nature",
    title: "Everyone Needs a Special 'Sit Spot' in Nature",
    text: `Ever since I read Richard Louv's influential book, "Last Child in the Woods," the idea of having a special "sit spot" has stuck with me. This advice, which Louv attributes to nature educator Jon Young, is for both adults and children to find...`,
    date: "November 4, 2020",
    source: "treehugger",
    link: "#",
  },
  {
    alt: "a dog",
    src: "https://i.imgflip.com/5s7g8s.png",
    keyword: "Nature",
    title: "Everyone Needs a Special 'Sit Spot' in Nature",
    text: `Ever since I read Richard Louv's influential book, "Last Child in the Woods," the idea of having a special "sit spot" has stuck with me. This advice, which Louv attributes to nature educator Jon Young, is for both adults and children to find...`,
    date: "November 4, 2020",
    source: "treehugger",
    link: "#",
  },
  {
    alt: "a dog",
    src: "https://i.imgflip.com/5s7g8s.png",
    keyword: "Nature",
    title: "Everyone Needs a Special 'Sit Spot' in Nature",
    text: `Ever since I read Richard Louv's influential book, "Last Child in the Woods," the idea of having a special "sit spot" has stuck with me. This advice, which Louv attributes to nature educator Jon Young, is for both adults and children to find...`,
    date: "November 4, 2020",
    source: "treehugger",
    link: "#",
  },
  {
    alt: "a dog",
    src: "https://i.imgflip.com/5s7g8s.png",
    keyword: "Nature",
    title: "Everyone Needs a Special 'Sit Spot' in Nature",
    text: `Ever since I read Richard Louv's influential book, "Last Child in the Woods," the idea of having a special "sit spot" has stuck with me. This advice, which Louv attributes to nature educator Jon Young, is for both adults and children to find...`,
    date: "November 4, 2020",
    source: "treehugger",
    link: "#",
  },
  {
    alt: "a dog",
    src: "https://i.imgflip.com/5s7g8s.png",
    keyword: "Nature",
    title: "Everyone Needs a Special 'Sit Spot' in Nature",
    text: `Ever since I read Richard Louv's influential book, "Last Child in the Woods," the idea of having a special "sit spot" has stuck with me. This advice, which Louv attributes to nature educator Jon Young, is for both adults and children to find...`,
    date: "November 4, 2020",
    source: "treehugger",
    link: "#",
  },
  {
    alt: "a dog",
    src: "https://i.imgflip.com/5s7g8s.png",
    keyword: "Nature",
    title: "Everyone Needs a Special 'Sit Spot' in Nature",
    text: `Ever since I read Richard Louv's influential book, "Last Child in the Woods," the idea of having a special "sit spot" has stuck with me. This advice, which Louv attributes to nature educator Jon Young, is for both adults and children to find...`,
    date: "November 4, 2020",
    source: "treehugger",
    link: "#",
  },
  {
    alt: "a dog",
    src: "https://i.imgflip.com/5s7g8s.png",
    keyword: "Nature",
    title: "Everyone Needs a Special 'Sit Spot' in Nature",
    text: `Ever since I read Richard Louv's influential book, "Last Child in the Woods," the idea of having a special "sit spot" has stuck with me. This advice, which Louv attributes to nature educator Jon Young, is for both adults and children to find...`,
    date: "November 4, 2020",
    source: "treehugger",
    link: "#",
  },
  {
    alt: "a dog",
    src: "https://i.imgflip.com/5s7g8s.png",
    keyword: "Nature",
    title: "Everyone Needs a Special 'Sit Spot' in Nature",
    text: `Ever since I read Richard Louv's influential book, "Last Child in the Woods," the idea of having a special "sit spot" has stuck with me. This advice, which Louv attributes to nature educator Jon Young, is for both adults and children to find...`,
    date: "November 4, 2020",
    source: "treehugger",
    link: "#",
  },
  {
    alt: "a dog",
    src: "https://i.imgflip.com/5s7g8s.png",
    keyword: "Nature",
    title: "Everyone Needs a Special 'Sit Spot' in Nature",
    text: `Ever since I read Richard Louv's influential book, "Last Child in the Woods," the idea of having a special "sit spot" has stuck with me. This advice, which Louv attributes to nature educator Jon Young, is for both adults and children to find...`,
    date: "November 4, 2020",
    source: "treehugger",
    link: "#",
  },
  {
    alt: "a dog",
    src: "https://i.imgflip.com/5s7g8s.png",
    keyword: "Nature",
    title: "Everyone Needs a Special 'Sit Spot' in Nature",
    text: `Ever since I read Richard Louv's influential book, "Last Child in the Woods," the idea of having a special "sit spot" has stuck with me. This advice, which Louv attributes to nature educator Jon Young, is for both adults and children to find...`,
    date: "November 4, 2020",
    source: "treehugger",
    link: "#",
  },
  {
    alt: "a dog",
    src: "https://i.imgflip.com/5s7g8s.png",
    keyword: "Nature",
    title: "Everyone Needs a Special 'Sit Spot' in Nature",
    text: `Ever since I read Richard Louv's influential book, "Last Child in the Woods," the idea of having a special "sit spot" has stuck with me. This advice, which Louv attributes to nature educator Jon Young, is for both adults and children to find...`,
    date: "November 4, 2020",
    source: "treehugger",
    link: "#",
  },
];
