export const cards = [
  {
    _id: 1,
    src: "",
    keyword: "Nature",
    title: "Everyone Needs a Special 'Sit Spot' in Nature",
    text: `Ever since I read Richard Louv's influential book, "Last Child in the Woods," the idea of having a special "sit spot" has stuck with me. This advice, which Louv attributes to nature educator Jon Young, is for both adults and children to find...`,
    date: "November 4, 2020",
    source: "treehugger",
    link: "#",
  },
  // {
  //     _id: ,
  //     src: '',
  //     keyword: ,
  //     title: ,
  //     text: ,
  //     date: ,
  //     source: ,
  //     link: #,
  // },
  // {
  //     _id: ,
  //     src: '',
  //     keyword: ,
  //     title: ,
  //     text: ,
  //     date: ,
  //     source: ,
  //     link: #,
  // },
  // {
  //     _id: ,
  //     src: '',
  //     keyword: ,
  //     title: ,
  //     text: ,
  //     date: ,
  //     source: ,
  //     link: #,
  // },
  // {
  //     _id: ,
  //     src: '',
  //     keyword: ,
  //     title: ,
  //     text: ,
  //     date: ,
  //     source: ,
  //     link: #,
  // },
];
